### ISSUE TITLE
Fly.io deploys failing, can't access base URL

### ISSUE THREAD

**Issue by jahabeebs** [gordalina/fly-tier#2]
Hi @gordalina!

In an effort to move off of tier.run's cloud service (since it's being eliminated) I followed your docs but the deployment doesn't seem to work.

When I try to access the base domain of my deployment (https://my-app-name.fly.dev) I get a simple "server not found" error both in postman and the browser. What should be the base URL that I use to replace my TIER_BASE_URL? Would it be "http://my-app-name.internal/"? and if so, would that mean I'd have to stand up nginx or some kind of proxy in fly.io to forward the request to http://my-app-name.internal/? Thank you for any advice or suggestions.

Here are the flyctl logs:

<img width="1270" alt="Screen Shot 2023-12-09 at 1 10 05 AM" src="https://github.com/gordalina/fly-tier/assets/47253537/ff5141d2-3fb2-479c-bdcf-71f3372b560b">

**Comment by gordalina** [comment]
I pushed a commit with changes to enable a public-facing interface, but I'd discourage from using it as it is not secure (as anyone can call that). Would you trying again?
